[package]
name = "advent-2024"
description.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
advtools.workspace = true

[dev-dependencies]
criterion = { version = "0.5", default-features = false }
