[package]
name = "advent19"
description = "Solutions for Advent of Code 2019."
version = "0.1.0"
authors = ["Georg Brandl <georg@python.org>"]
edition = "2018"

[[bench]]
name = "days"
harness = false

[dependencies]
advtools = { version = "0.5.0", path = "../advtools" }
num = "0.2.0"
rand = "0.7.2"
float-ord = "0.2.0"
generic-array = "0.13.2"
num_enum = "0.4.2"
bit = "0.1.1"

[dev-dependencies]
criterion = { version = "0.3.0", default-features = false }
