[package]
name = "advent16"
description = "Solutions for Advent of Code 2016."
version = "0.1.0"
authors = ["Georg Brandl <georg@python.org>"]

[dependencies]
advtools = "0.2.3"
md-5 = "0.8.0"
itoa = "0.4.3"
strum = "0.12.0"
strum_macros = "0.12.0"
