[package]
name = "advent-2016"
description.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
advtools.workspace = true
md-5 = "0.10"
itoa = "1.0"

[dev-dependencies]
criterion = { version = "0.5", default-features = false }
