[package]
name = "advent16"
description = "Solutions for Advent of Code 2016."
version = "0.1.0"
authors = ["Georg Brandl <georg@python.org>"]

[dependencies]
odds = "*"
rayon = "*"
md-5 = "*"
strum = "*"
strum_macros = "*"
itoa = "*"

[dependencies.advtools]
path = "advtools"
