[package]
name = "advent16"
description = "Solutions for Advent of Code 2016."
version = "0.1.0"
authors = ["Georg Brandl <georg@python.org>"]

[dependencies]
advtools = "0.2.1"
rayon = "1.0"
md-5 = "0.8"
strum = "0.11"
strum_macros = "0.11"
itoa = "0.4"
