[package]
name = "advent16"
description = "Solutions for Advent of Code 2016."
version = "0.1.0"
authors = ["Georg Brandl <georg@python.org>"]

[dependencies]
advtools = { git = "https://github.com/birkenfeld/advtools" }
odds = "*"
rayon = "*"
md-5 = "*"
strum = "*"
strum_macros = "*"
itoa = "*"
