[package]
name = "day19"
version = "0.1.0"
authors = ["Georg Brandl <georg@python.org>"]

[[bin]]
name = "day19"
path = "main.rs"

[dependencies]
rand = "*"

[dependencies.advtools]
path = "../advtools"
