[package]
name = "advtools"
description = "A prelude to reduce boilerplate of 'Advent of Code' like challenges."
version = "0.6.0"
authors = ["Georg Brandl <georg@python.org>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/birkenfeld/advtools"
edition = "2018"

[dependencies]
itertools = "0.9.0"
hashbrown = "0.9.1"
arrayvec = "0.5.2"
rayon = "1.5.0"
regex = "1.4.2"
num = "0.3.1"
odds = { version = "0.4.0", features = ["std-string", "std-vec"] }
# try
arraytools = "0.1.5"
