[package]
name = "advtools"
description = "A prelude to reduce boilerplate of 'Advent of Code' like challenges."
version = "0.2.2"
authors = ["Georg Brandl <georg@python.org>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/birkenfeld/advtools"

[dependencies]
itertools = "0.7"
arrayvec = "0.4"
fxhash = "0.2"
rayon = "1.0"
regex = "1.1"
odds = "0.3"
