[package]
name = "day05"
version = "0.1.0"
authors = ["Georg Brandl <georg@python.org>"]

[[bin]]
name = "day05"
path = "main.rs"

[dependencies]
arrayvec = "*"
md-5 = "*"
rayon = "*"

[dependencies.advtools]
path = "../advtools"
