[package]
name = "day17"
version = "0.1.0"
authors = ["Georg Brandl <georg@python.org>"]

[[bin]]
name = "day17"
path = "main.rs"

[dependencies]
rust-crypto = "*"
rayon = { git = "https://github.com/nikomatsakis/rayon" }
