[package]
name = "day02"
version = "0.1.0"
authors = ["Georg Brandl <georg@python.org>"]

[[bin]]
name = "day02"
path = "main.rs"

[dependencies]
itertools = "*"
strum = "*"
strum_macros = "*"

[dependencies.advtools]
path = "../advtools"
