[package]
name = "day07"
version = "0.1.0"
authors = ["Georg Brandl <georg@python.org>"]

[[bin]]
name = "day07"
path = "main.rs"

[dependencies]
itertools = "*"

[dependencies.advtools]
path = "../advtools"
