[package]
name = "day09"
version = "0.1.0"
authors = ["Georg Brandl <georg@python.org>"]

[[bin]]
name = "day09"
path = "main.rs"

[dependencies]
permutohedron = "*"

[dependencies.advtools]
path = "../advtools"
